spring.application.name=OOP

# TODO: set your MySQL connection URL, username, and password
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/HomeTutor?sslMode=REQUIRED
spring.datasource.username=FotiQ2JnGUaF2eR.root
spring.datasource.password=VXHoVAltqxpgTg5F

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#prme hhrq vstd jvhp

